/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardWatchlistImport } from './routes/dashboard/watchlist'
import { Route as DashboardSummaryImport } from './routes/dashboard/summary'
import { Route as DashboardSellImport } from './routes/dashboard/sell'
import { Route as DashboardAuctionsImport } from './routes/dashboard/auctions'
import { Route as DashboardAuctionsAuctionIdImport } from './routes/dashboard/auctions.$auctionId'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardWatchlistRoute = DashboardWatchlistImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSummaryRoute = DashboardSummaryImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardSellRoute = DashboardSellImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardAuctionsRoute = DashboardAuctionsImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardAuctionsAuctionIdRoute = DashboardAuctionsAuctionIdImport.update(
  {
    id: '/$auctionId',
    path: '/$auctionId',
    getParentRoute: () => DashboardAuctionsRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/auctions': {
      id: '/dashboard/auctions'
      path: '/auctions'
      fullPath: '/dashboard/auctions'
      preLoaderRoute: typeof DashboardAuctionsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/sell': {
      id: '/dashboard/sell'
      path: '/sell'
      fullPath: '/dashboard/sell'
      preLoaderRoute: typeof DashboardSellImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/summary': {
      id: '/dashboard/summary'
      path: '/summary'
      fullPath: '/dashboard/summary'
      preLoaderRoute: typeof DashboardSummaryImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/watchlist': {
      id: '/dashboard/watchlist'
      path: '/watchlist'
      fullPath: '/dashboard/watchlist'
      preLoaderRoute: typeof DashboardWatchlistImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/auctions/$auctionId': {
      id: '/dashboard/auctions/$auctionId'
      path: '/$auctionId'
      fullPath: '/dashboard/auctions/$auctionId'
      preLoaderRoute: typeof DashboardAuctionsAuctionIdImport
      parentRoute: typeof DashboardAuctionsImport
    }
  }
}

// Create and export the route tree

interface DashboardAuctionsRouteChildren {
  DashboardAuctionsAuctionIdRoute: typeof DashboardAuctionsAuctionIdRoute
}

const DashboardAuctionsRouteChildren: DashboardAuctionsRouteChildren = {
  DashboardAuctionsAuctionIdRoute: DashboardAuctionsAuctionIdRoute,
}

const DashboardAuctionsRouteWithChildren =
  DashboardAuctionsRoute._addFileChildren(DashboardAuctionsRouteChildren)

interface DashboardRouteChildren {
  DashboardAuctionsRoute: typeof DashboardAuctionsRouteWithChildren
  DashboardSellRoute: typeof DashboardSellRoute
  DashboardSummaryRoute: typeof DashboardSummaryRoute
  DashboardWatchlistRoute: typeof DashboardWatchlistRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAuctionsRoute: DashboardAuctionsRouteWithChildren,
  DashboardSellRoute: DashboardSellRoute,
  DashboardSummaryRoute: DashboardSummaryRoute,
  DashboardWatchlistRoute: DashboardWatchlistRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/auctions': typeof DashboardAuctionsRouteWithChildren
  '/dashboard/sell': typeof DashboardSellRoute
  '/dashboard/summary': typeof DashboardSummaryRoute
  '/dashboard/watchlist': typeof DashboardWatchlistRoute
  '/dashboard/auctions/$auctionId': typeof DashboardAuctionsAuctionIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/auctions': typeof DashboardAuctionsRouteWithChildren
  '/dashboard/sell': typeof DashboardSellRoute
  '/dashboard/summary': typeof DashboardSummaryRoute
  '/dashboard/watchlist': typeof DashboardWatchlistRoute
  '/dashboard/auctions/$auctionId': typeof DashboardAuctionsAuctionIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/auctions': typeof DashboardAuctionsRouteWithChildren
  '/dashboard/sell': typeof DashboardSellRoute
  '/dashboard/summary': typeof DashboardSummaryRoute
  '/dashboard/watchlist': typeof DashboardWatchlistRoute
  '/dashboard/auctions/$auctionId': typeof DashboardAuctionsAuctionIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/dashboard/auctions'
    | '/dashboard/sell'
    | '/dashboard/summary'
    | '/dashboard/watchlist'
    | '/dashboard/auctions/$auctionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/dashboard/auctions'
    | '/dashboard/sell'
    | '/dashboard/summary'
    | '/dashboard/watchlist'
    | '/dashboard/auctions/$auctionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/dashboard/auctions'
    | '/dashboard/sell'
    | '/dashboard/summary'
    | '/dashboard/watchlist'
    | '/dashboard/auctions/$auctionId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/auctions",
        "/dashboard/sell",
        "/dashboard/summary",
        "/dashboard/watchlist"
      ]
    },
    "/dashboard/auctions": {
      "filePath": "dashboard/auctions.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/auctions/$auctionId"
      ]
    },
    "/dashboard/sell": {
      "filePath": "dashboard/sell.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/summary": {
      "filePath": "dashboard/summary.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/watchlist": {
      "filePath": "dashboard/watchlist.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/auctions/$auctionId": {
      "filePath": "dashboard/auctions.$auctionId.tsx",
      "parent": "/dashboard/auctions"
    }
  }
}
ROUTE_MANIFEST_END */
