services:
  ### DATABASES
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/:ro
    ports:
      - "5433:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./initmq/definitions.json:/etc/rabbitmq/definitions:ro
    networks:
      - app-network

  ### APIS
  auction-service:
    build:
      context: ./auction-service
      dockerfile: Dockerfile
    container_name: auction-service
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres-db:5432/auction_service_db"
      RABBITMQ_HOST: "rabbitmq"
      ADMIN_USERID: "c1bba5c0-b001-7085-7a2e-e74d5399c3d1"
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "localhost:4000/healthcheck"]
    networks:
      - app-network

  notification-service:
    restart: always
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "4001:4001"
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres-db:5432/notification_service_db"
      RABBITMQ_HOST: "rabbitmq"
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "localhost:4001/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  api-gateway:
    restart: always
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "42069:42069" # API Gateway exposed on port 3000
    healthcheck:
      test: ["CMD", "curl", "localhost:42069/healthcheck"]
    depends_on:
      auction-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  user-service:
    build:
      context: ./userService
    container_name: user-service
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - 8080:8080
    entrypoint:
      ["java", "-jar", "-Dspring.profiles.active=docker", "application.jar"]
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  initdb:
