# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# set username and password
ENV MONGO_INITDB_ROOT_USERNAME=myUsername
ENV MONGO_INITDB_ROOT_PASSWORD=myPassword

# Expose MongoDB port (default 27017)
EXPOSE 27017

# Default command to run MongoDB server
CMD ["mongod"]

