version: '3.9'

services:
  mongodb:
    build:
      context: ./mongodb/
      dockerfile: Dockerfile
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
        test: ["CMD-SHELL", "pgrep mongod > /dev/null || exit 1"]
        interval: 10s
        timeout: 10s
        retries: 10

  rabbitmq_consumer:
    build:
      context: .
      dockerfile: cart-rabbitmq/Dockerfile
    container_name: rabbitmq_consumer
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      MONGO_URI: "mongodb://mongodb:27017/shopping_cart"
      RABBITMQ_HOST: "rabbitmq"

  shopping_cart_service:
    build:
      context: .
      dockerfile: cart-flask/Dockerfile
    container_name: shopping_cart_service
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
          condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      MONGO_URI: "mongodb://mongodb:27017/shopping_cart"
      RABBITMQ_HOST: "rabbitmq"

volumes:
  mongo_data:
